import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import Modal from "./components/modals/modal";
import LoginModal from "./components/modals/LoginModal";
import SignUpModal from "./components/modals/SignUpModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "landRental",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>

        <div className="pt-32">
        {children}
        </div>

       <LoginModal/>
       <SignUpModal/>
        </body>
    </html>
  );
}
